export default {
    login: 'api/user/login',
    banner: 'api/banner',
    book: 'api/book',
    chapter: 'api/chapter',
    category:'api/category/category',
    category1:'api/category/category1',
    category2:'api/category/category2',
    userBook: 'api/usersBook',
    getListByName: 'api/book/getListByName',
    video:'api/video',
    music:'api/music',
    goods:'api/goods',
    article:'api/article',
    order:'api/order',
};
